#!/bin/bash -l
#SBATCH -J array_job
#SBATCH -t 24:00:00
#SBATCH -p high
#SBATCH --cpus-per-task=8
module load bio
PROJECTROOT=/home/seboles/abaloneraw/male_lane456_diginorm/EXTRACT/ 
gzip -9c orphans.qc.fq.gz.keep.abundfilt > orphans.keep.abundfilt.fq.gz && \
  rm orphans.qc.fq.gz.keep.abundfilt
for file in $PROJECTROOT/*.pe.*.abundfilt.se
do
  gzip -9c ${file} >> orphans.keep.abundfilt.fq.gz && \
  rm ${file}
done
