---
title: "Red Abalone Reference Transcriptome - Post-Diginorm Stats Lane 4 & Lane 5"
author: "Sara E. Boles"
date: "07/09/2017"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# This is post-diginorm stats for lane 4 and lane 5 female tissues only. Here are the summary statics.
```{r}
library(wesanderson)
library(ggplot2)
library(stats)
library(devtools)
library(jsonlite)
abalone<-read.csv("post-diginormlane4lane5female.csv")
summary(abalone)
plot(abalone)
```
   
```{r Post-Diginorm Stats Total K-mer Count,fig.width=8,fig.height=6}
p=ggplot(abalone,aes(Library,Total,fill=Library))+geom_boxplot()
p+scale_y_continuous(name="Number of K-mers")+theme_bw()+ggtitle("Post-Diginorm Stats\n Lane 4 & Lane 5 Female Tissues\n Combined Total K-mer Count")+theme(strip.text.x=element_text(size=20))+theme(plot.title=element_text(size = 20,face="bold",hjust = 0.5))+theme(axis.text=element_text(size=12,angle=90),axis.title=element_text(size=14,face="bold"))
```

```{r Post-Diginorm Stats Unique K-Mers Kept, fig.width=8,fig.height=6}
p=ggplot(abalone,aes(Library,Kept,fill=Library))+geom_boxplot()
p+scale_y_continuous(name="Total Unique\n K-mers Kept")+theme_bw()+ggtitle("Post-Diginorm Stats\n Lane 4 & Lane 5 Female Tissues Combined:\n Unique K-mers Kept")+theme(strip.text.x=element_text(size=20))+theme(plot.title=element_text(size = 20,face="bold",hjust = 0.5))+theme(axis.text=element_text(size=12,angle=90),axis.title=element_text(size=14,face="bold"))
```
 
```{r Post-Diginorm Stats Separately, fig.width=8,fig.height=6}
p=ggplot(abalone,aes(Library,Kept,fill=Library))+geom_boxplot()
p+scale_y_continuous(name="Total Unique\n K-mers Kept")+theme_bw()+ggtitle("Post-Diginorm Stats\n Lane 4 & Lane 5 Female Tissues Separately")+theme(strip.text.x=element_text(size=11))+theme(plot.title=element_text(size = 11,face="bold",hjust = 0.5))+theme(axis.text=element_text(size=12,angle=90),axis.title=element_text(size=14,face="bold"))+facet_grid(.~Lane)
```

```{r Post-Diginorm Stats Percent Unique K-mers Kept, fig.width=8,fig.height=6}
p=ggplot(abalone,aes(Library,Percent,fill=Library))+geom_boxplot()
p+scale_y_continuous(name="Percent Unique\n K-mers Kept")+theme_bw()+ggtitle("Post-Diginorm Stats\n Lane 4 & Lane 5 Female Tissues Combined")+theme(strip.text.x=element_text(size=20))+theme(plot.title=element_text(size = 20,face="bold",hjust = 0.5))+theme(axis.text=element_text(size=12,angle=90),axis.title=element_text(size=14,face="bold"))
```

```{r Post-Diginorm Stats Percent Unique K-mers Kept By Lane, fig.width=8,fig.height=6}
p=ggplot(abalone,aes(Library,Percent,fill=Library))+geom_boxplot()
p+scale_y_continuous(name="Percent Unique\n K-mers Kept")+theme_bw()+ggtitle("Post-Diginorm Stats\n Lane 4 & Lane 5 Female Tissues")+theme(strip.text.x=element_text(size=11))+theme(plot.title=element_text(size = 11,face="bold",hjust = 0.5))+theme(axis.text=element_text(size=12,angle=90),axis.title=element_text(size=14,face="bold"))+facet_grid(.~Lane)
```


